//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRENCHISEREPORT
    {
        public int FRID { get; set; }
        public Nullable<int> FUID { get; set; }
        public string DATE { get; set; }
        public string OB { get; set; }
        public string AR { get; set; }
        public string AP { get; set; }
        public string AW { get; set; }
        public string CB { get; set; }
        public string OCPL { get; set; }
        public string MCCB { get; set; }
        public string MCC { get; set; }
        public string MCD { get; set; }
        public string MP { get; set; }
        public string MW { get; set; }
        public string MCPL { get; set; }
    }
}
