//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMEPOOL
    {
        public int GPID { get; set; }
        public Nullable<int> GSID { get; set; }
        public string GSTIME { get; set; }
        public string GSENDTIME { get; set; }
        public string GPDATE { get; set; }
        public string GPRESULT { get; set; }
        public Nullable<int> YID { get; set; }
        public string JACKPOT { get; set; }
    }
}
