//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_db1Entities : DbContext
    {
        public admin_db1Entities()
            : base("name=admin_db1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINUSER> ADMINUSERs { get; set; }
        public DbSet<AFTXN> AFTXNs { get; set; }
        public DbSet<FRENCHISE> FRENCHISEs { get; set; }
        public DbSet<FRENCHISEBAL> FRENCHISEBALs { get; set; }
        public DbSet<FUTXN> FUTXNs { get; set; }
        public DbSet<GAMEPOOL> GAMEPOOLs { get; set; }
        public DbSet<GAMESLOT> GAMESLOTs { get; set; }
        public DbSet<Recipt> Recipts { get; set; }
        public DbSet<TOTALSALE> TOTALSALEs { get; set; }
        public DbSet<USERBAL> USERBALs { get; set; }
        public DbSet<USERTBL> USERTBLs { get; set; }
        public DbSet<YANTRA> YANTRAs { get; set; }
        public DbSet<FRENCHISEREPORT> FRENCHISEREPORTs { get; set; }
    }
}
