//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipt
    {
        public int RID { get; set; }
        public Nullable<int> FUID { get; set; }
        public Nullable<int> UUID { get; set; }
        public string RTYPE { get; set; }
        public string Y1 { get; set; }
        public string Y2 { get; set; }
        public string Y3 { get; set; }
        public string Y4 { get; set; }
        public string Y5 { get; set; }
        public string Y6 { get; set; }
        public string Y7 { get; set; }
        public string Y8 { get; set; }
        public string Y9 { get; set; }
        public string Y10 { get; set; }
        public string GSID { get; set; }
        public string GSTIME { get; set; }
        public string GSDATE { get; set; }
        public string RGTIME { get; set; }
        public string RVAL { get; set; }
        public string RWINVAL { get; set; }
        public string RSTATUS { get; set; }
    }
}
