//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOTALSALE
    {
        public int TSID { get; set; }
        public Nullable<int> GSID { get; set; }
        public Nullable<int> GPID { get; set; }
        public string GPSTIME { get; set; }
        public string GPSENDTIME { get; set; }
        public string GPDATE { get; set; }
        public string Y1 { get; set; }
        public string Y2 { get; set; }
        public string Y3 { get; set; }
        public string Y4 { get; set; }
        public string Y5 { get; set; }
        public string Y6 { get; set; }
        public string Y7 { get; set; }
        public string Y8 { get; set; }
        public string Y9 { get; set; }
        public string Y10 { get; set; }
    }
}
