//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERBAL
    {
        public int UWID { get; set; }
        public string BALANCE { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> FUID { get; set; }
    }
}
