//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTBL
    {
        public int UID { get; set; }
        public string FUID { get; set; }
        public string UUNAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string CONTACTNO { get; set; }
    }
}
