//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YANTRA
    {
        public int YID { get; set; }
        public string YANTRANAME { get; set; }
        public Nullable<decimal> YANTRASELLPRICE { get; set; }
        public string YANTRAIMAGEURL { get; set; }
    }
}
